---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geovbra-test-redis-pvc
  labels:
    username: geovbra
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi