---
apiVersion: v1
kind: Service
metadata:
  name: geovbra-test-redis-service
  labels:
    name: geovbra
    env: test
spec:
  type: ClusterIP
  selector:
    username: geovbra
    env: test
    app: geovbra-test-redis
  ports:
  - name: geovbra-test-redis-port
    port: 6379
    targetPort: 6379