---
apiVersion: v1
kind: Service
metadata:
  name: geovbra-test-flask-service
  labels:
    name: geovbra
    env: test
spec:
  type: ClusterIP
  selector:
    username: geovbra
    env: test
    app: geovbra-test-flask
  ports:
  - name: geovbra-test-flask-port
    port: 5000
    targetPort: 5005